version: '3'

services:
   mysql57:
     image: mysql:5.7
     container_name: mysql57
     restart: always
     volumes:
       - pwe_mysql57:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root123
       MYSQL_DATABASE: pwe
       MYSQL_USER: pwe
       MYSQL_PASSWORD: pwe
   nginx:
     image: nginx
     ports:
       - "8080:80"
     volumes:
       - pwe_source:/PWE
       - pwe_project:/PWE/webapps/mywebproject.ltd
     restart: always
     depends_on:
       - pwe
   pwe:
     depends_on:
       - mysql57
     image: pwe:latest
     restart: always
     container_name: pwe
     volumes:
       - pwe_source:/PWE
       - pwe_project:/PWE/webapps/mywebproject.ltd
     deploy:
       replicas: 1
     ports:
       - "7779:9999"
     working_dir: /PWE/examples/static_web # Set te path to your owner project
     command:
       - ./pwe.fcgi
     stdin_open: true
     tty: true
     environment:
       FCGI_SOCKET_PATH: :9999
       PWE_CONF_DB1_HOST: db
       PWE_CONF_DB1_PORT: 3306
       PWE_CONF_DB1_DBNAME: pwe
       PWE_CONF_DB1_USER: pwe
       PWE_CONF_DB1_PASS: pwe
volumes:
    pwe_source:
    pwe_mysql57:
    pwe_project:
