version: '3'

services:
   mysql57:
     image: mysql:5.7
     container_name: mysql57
     restart: always
     volumes:
       - pwe_mysql57:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root123
       MYSQL_DATABASE: pwe
       MYSQL_USER: pwe
       MYSQL_PASSWORD: pwe
   nginx:
     image: nginx:alpine
     restart: always
     container_name: nginx
     stdin_open: true
     tty: true
     volumes:
       #- /etc/nginx/docker.conf:/etc/nginx/conf.d/default.conf
       - pwe_source:/PWE:ro
       - pwe_project:/PWE/webapps/mywebproject.ltd:ro
       - pwe_nginx:/NGINX/:ro
     ports:
       - "8081:80"
     command: /bin/sh -c "apk update && apk add bash && rm -fr /var/cache/apk/* && cat /NGINX/generic/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
     depends_on:
       - pwe
   pwe:
     depends_on:
       - mysql57
     image: pwe:latest
     restart: always
     container_name: pwe
     volumes:
       - pwe_source:/PWE
       - pwe_project:/PWE/webapps/mywebproject.ltd
       - pwe_nginx:/NGINX
     deploy:
       replicas: 1
     ports:
       - "7779:9999"
     working_dir: /PWE/examples/generic_web # Set te path to your owner project
     command:
       - ./pwe.fcgi
     stdin_open: true
     tty: true
     environment:
       FCGI_SOCKET_PATH: :9999
       PWE_CONF_DB1_HOST: mysql57
       PWE_CONF_DB1_PORT: 3306
       PWE_CONF_DB1_DBNAME: pwe
       PWE_CONF_DB1_USER: pwe
       PWE_CONF_DB1_PASS: pwe
volumes:
    pwe_source:
    pwe_nginx:
    pwe_mysql57:
    pwe_project:
