version: '3.4'

services:
   pwe:
     image: kukam/pwe
     volumes:
       - source:/PWE
       - project:/PWE/examples/generic_web
       #- project:/PWE/examples/static_web
       #- project:/PWE/webapps/mydomain.ltd # Set the path to your owner project and remove bind generic_web and static_web.
     restart: on-failure
   mariadb:
     image: kukam/pwe-mariadb
     restart: always
     volumes:
       - mariadb:/var/lib/mysql
     environment:
       MYSQL_ROOT_PWD: root123
       MYSQL_USER_DB: pwe
       MYSQL_USER: pwe
       MYSQL_USER_PWD: pwe
   fastcgi:
     image: kukam/pwe-fastcgi
     container_name: fastcgi
     restart: unless-stopped
     deploy:
       replicas: 1
       restart_policy:
         condition: on-failure
         delay: 5s
         window: 120s
     volumes:
       - source:/PWE
       - project:/PWE/webapps/mydomain.ltd # # Set the path to your owner project
     ports:
       - "7779:7779"
     working_dir: /PWE/webapps/mydomain.ltd # Set the path to your owner project
     stdin_open: true
     tty: true
     depends_on:
       - "mariadb"
       - "pwe"
     environment:
       FCGI_SOCKET_PATH: :7779
       PWE-CONF-pwe-home: "/PWE/webapps/mydomain.ltd/" # Set the path to your owner project
       PWE-CONF-dbi-db1-host: mariadb
       PWE-CONF-dbi-db1-port: 3306
       PWE-CONF-dbi-db1-dbname: pwe
       PWE-CONF-dbi-db1-user: pwe
       PWE-CONF-dbi-db1-pass: pwe
       PWE-CONF-log-logout: "STDERR"
       PWE-CONF-log-loglevel: 1
       PWE-CONF-log-log_delay: 1
       PWE-CONF-log-log_delay_minimum: "0.1"
   nginx:
     image: kukam/pwe-nginx
     restart: always
     stdin_open: true
     tty: true
     links:
       - fastcgi:fastcgi
     volumes:
       - source:/PWE
       - project:/PWE/webapps/nginx/:ro
     ports:
       - "7778:80"
     depends_on:
       - "mariadb"
       - "fastcgi"
       - "pwe"
volumes:
    source:
    nginx:
    mariadb:
    project:
