version: '3'

# Todle v dokumentaci neni...
#services:
#   fastcgi:
#     working_dir: path/

services:
   pwe:
     image: kukam/pwe
     volumes:
       - source:/PWE
     restart: on-failure
   pwe-myproject:
     image: kukam/pwe-myproject
     volumes:
       - project:/PWE/webapps/myproject
     restart: on-failure
   mariadb:
     image: kukam/pwe-mariadb
     restart: unless-stopped
     volumes:
       - mariadb:/var/lib/mysql
     environment:
       MYSQL_ADMIN_PWD: ${DB_ADMIN_PWD:-root123}
       MYSQL_USER_DB: ${DB_USER_DB:-pwe}
       MYSQL_USER: ${DB_USER:-pwe}
       MYSQL_USER_PWD: ${DB_USER_PWD:-pwe}
   postgresdb:
     image: kukam/pwe-postgresdb
     restart: unless-stopped
     volumes:
       - postgresdb:/var/lib/postgresql/data
     environment:
       POSTGRES_ADMIN_PWD: ${DB_ADMIN_PWD:-root123}
       POSTGRES_USER_DB: ${DB_USER_DB:-pwe}
       POSTGRES_USER: ${DB_USER:-pwe}
       POSTGRES_USER_PWD: ${DB_USER_PWD:-pwe}
   fastcgi:
     image: kukam/pwe-fastcgi
     restart: unless-stopped
     volumes:
       - source:/PWE
       - project:/PWE/webapps/myproject
       - uploadfile:/PWE/webapps/myproject/uploadfile
     stdin_open: true
     tty: true
     environment:
       FCGI_SOCKET_PATH: :7779
       PWE_CONF_pwe_save_opt_to: db
       PWE_CONF_pwe_home: /PWE/webapps/myproject/
       PWE_CONF_pwe_upload_dir: uploadfile/
       PWE_CONF_pwe_opts_dir: sessions/
       PWE_CONF_dbi_db1_dbdriver: ${PWE_DB_DRIVER:-MySQL}
       PWE_CONF_dbi_db1_host: ${PWE_DB_HOST:-mariadb}
       PWE_CONF_dbi_db1_port: ${PWE_DB_PORT:-3306}
       PWE_CONF_dbi_db1_schema: public
       PWE_CONF_dbi_db1_database: ${DB_USER_DB:-pwe}
       PWE_CONF_dbi_db1_login: ${DB_USER:-pwe}
       PWE_CONF_dbi_db1_password: ${DB_USER_PWD:-pwe}
       PWE_CONF_dbi_db1_dbversion_file: ${PWE_DB_DBVERSION:-conf/mysql_dbversion.pl}
       PWE_CONF_log_logout: STDERR
       PWE_CONF_log_loglevel: 3
       PWE_CONF_log_log_delay: 1
       PWE_CONF_log_log_delay_minimum: 0.1
   nginx:
     image: kukam/pwe-nginx
     restart: unless-stopped
     stdin_open: true
     tty: true
     volumes:
       - source:/PWE
       - project:/PWE/webapps/myproject
       - uploadfile:/PWE/webapps/myproject/uploadfile
     ports:
       - "7778:80"
volumes:
    source: 		# PWE core code
    mariadb:		# Mariadb volume
    postgresdb:		# Postgresdb volume
    project:		# My webpage
    uploadfile:		# Uploadfile
