version: '3'

services:
   pwe:
     image: kukam/pwe
     volumes:
       - source:/PWE
       - project:/PWE/examples/generic_web
       #- project:/PWE/examples/static_web
       #- project:/PWE/webapps/mydomain.ltd # Set the path to your owner project and remove bind generic_web and static_web.
     restart: on-failure
   mariadb:
     image: kukam/pwe-mariadb
     restart: unless-stopped
     volumes:
       - mariadb:/var/lib/mysql
     environment:
       MYSQL_ROOT_PWD: root123
       MYSQL_USER_DB: pwe
       MYSQL_USER: pwe
       MYSQL_USER_PWD: pwe
   postgresdb:
     image: kukam/pwe-postgresdb
     restart: unless-stopped
     volumes:
       - postgresdb:/var/lib/postgresql
     environment:
       POSTGRES_ADMIN_PASS: root123
       POSTGRES_USER_DB: pwe
       POSTGRES_USER: pwe
       POSTGRES_USER_PASS: pwe
   fastcgi:
     image: kukam/pwe-fastcgi
     container_name: fastcgi
     restart: unless-stopped
     volumes:
       - source:/PWE
       - project:/PWE/webapps/mydomain.ltd # Set the path to your owner project
       - uploadfile:/PWE/webapps/mydomain.ltd/uploadfile # Set the path to your owner project
     working_dir: /PWE/webapps/mydomain.ltd # Set the path to your owner project
     stdin_open: true
     tty: true
     depends_on:
       - "mariadb"
       - "pwe"
     environment:
       FCGI_SOCKET_PATH: :7779
       PWE-CONF-pwe-save_opt_to: "db"
       PWE-CONF-pwe-home: "/PWE/webapps/mydomain.ltd/" # Set the path to your owner project
       PWE-CONF-pwe-upload_dir: "uploadfile/"
       PWE-CONF-pwe-opts_dir: "sessions/"
       PWE-CONF-dbi-db1-host: mariadb
       PWE-CONF-dbi-db1-port: 3306
       PWE-CONF-dbi-db1-dbname: pwe
       PWE-CONF-dbi-db1-user: pwe
       PWE-CONF-dbi-db1-pass: pwe
       PWE-CONF-log-logout: "STDERR"
       PWE-CONF-log-loglevel: 1
       PWE-CONF-log-log_delay: 1
       PWE-CONF-log-log_delay_minimum: "0.1"
   nginx:
     image: kukam/pwe-nginx
     restart: unless-stopped
     stdin_open: true
     tty: true
     volumes:
       - source:/PWE
       - project:/PWE/webapps/nginx
       - uploadfile:/PWE/webapps/nginx/uploadfile
     ports:
       - "7778:80"
     depends_on:
       - "mariadb"
       - "fastcgi"
       - "pwe"
volumes:
    source: 		# PWE core code
    mariadb:		# Mariadb volume
    postgresdb:		# Postgresdb volume
    project:		# My webpage
    uploadfile:		# Uploadfile
