version: '3'

services:
   pwe:
     image: kukam/pwe
     volumes:
       - source:/PWE
     restart: on-failure
   mariadb:
     image: kukam/pwe-mariadb
     restart: always
     volumes:
       - mariadb:/var/lib/mysql
     environment:
       MYSQL_ROOT_PWD: root123
       MYSQL_USER_DB: pwe
       MYSQL_USER: pwe
       MYSQL_USER_PWD: pwe
   fastcgi:
     image: kukam/pwe-fastcgi
     restart: always
     volumes:
       - source:/PWE
       #- source:/PWE:ro
       #- project:/PWE/webapps/mydomain.ltd # Uncoment te path to your owner project
     deploy:
       replicas: 1
     ports:
       - "7779:7779"
     #working_dir: /PWE/examples/generic_web # Set te path to your owner project
     #command:
     #  - ./pwe.fcgi
     stdin_open: true
     tty: true
     environment:
       FCGI_SOCKET_PATH: :7779
       PWE_CONF_db1_host: mariadb
       PWE_CONF_db1_port: 3306
       PWE_CONF_db1_dbname: pwe
       PWE_CONF_db1_user: pwe
       PWE_CONF_db1_pass: pwe
       PWE_CONF_home: "/PWE/examples/generic_web"
   nginx:
     image: kukam/pwe-nginx
     restart: always
     stdin_open: true
     tty: true
     volumes:
       - source:/PWE:ro
       #- project:/PWE/webapps/mydomain.ltd:ro # Uncoment te path to your owner project
     ports:
       - "7778:80"       
     environment:
       PWE_CONF_home: "/PWE/examples/generic_web"
volumes:
    source:
    nginx:
    mariadb:
    project:
