version: '3'

services:
   database:
     image: kukam/pwe-${DB_DRIVER:-maria}
     restart: unless-stopped
     volumes:
       - ${DB_DRIVER:-maria}:/dbhome
       - /etc/localtime:/etc/localtime:ro
     deploy:
       placement:
         constraints:
           - node.role == manager
     environment:
       DB_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD:-root123}
       DB_NAME: ${DB_NAME:-pwe}
       DB_USER: ${DB_USER:-pwe}
       DB_USER_PASSWORD: ${DB_USER_PASSWORD:-pwe}
   pwe:
     image: kukam/pwe
     restart: unless-stopped
     volumes:
       - myproject:/PWE/webapps/myproject
       - uploadfile:/PWE/webapps/myproject/uploadfile
       - /etc/localtime:/etc/localtime:ro
     stdin_open: true
     tty: true
     environment:
       PWESOURCE: "https://github.com/kukam/PWE/trunk"
       MYPROJECT: "https://github.com/kukam/PWE/trunk/examples/generic_web"
       FCGI_SOCKET_PATH: :7779
       PWE_CONF_pwe_save_opt_to: db
       PWE_CONF_pwe_assets_dir: assets, uploadfile/
       PWE_CONF_pwe_upload_dir: uploadfile/
       PWE_CONF_pwe_assets_browse_dir: uploadfile/
       PWE_CONF_pwe_opts_dir: sessions/
       PWE_CONF_dbi_db1_dbdriver: ${DB_DRIVER:-maria}
       PWE_CONF_dbi_db1_host: database
       PWE_CONF_dbi_db1_port: 7775
       PWE_CONF_dbi_db1_schema: public
       PWE_CONF_dbi_db1_database: ${DB_NAME:-pwe}
       PWE_CONF_dbi_db1_login: ${DB_USER:-pwe}
       PWE_CONF_dbi_db1_password: ${DB_USER_PASSWORD:-pwe}
       PWE_CONF_dbi_db1_dbversion_file: conf/${DB_DRIVER:-maria}_dbversion.pl
       PWE_CONF_dbi_db1_trayconnect: 10
       PWE_CONF_log_logout: STDERR
       PWE_CONF_log_loglevel: 3
       PWE_CONF_log_log_delay: 1
       PWE_CONF_log_log_delay_minimum: 0.1
   webproxy:
     image: kukam/pwe-${WEBSERVER_NAME:-nginx}
     restart: unless-stopped
     stdin_open: true
     tty: true
     ports:
       - "7778:80"
     volumes:
       - /etc/localtime:/etc/localtime:ro

volumes:
    myproject:    # MYPROJECT VOLUME
    uploadfile:   # folder for uploadfile
    maria:        # Maria volume
    postgres:     # Postgres volume
