version: '3'

services:
   mariadb:
     image: kukam/pwe-mariadb
     container_name: mysql57
     restart: always
     volumes:
       - mariadb:/var/lib/mysql
     environment:
       MYSQL_ROOT_PWD: root123
       MYSQL_USER_DB: pwe
       MYSQL_USER: pwe
       MYSQL_USER_PWD: pwe
   fastcgi:
     image: kukam/pwe
     restart: always
     container_name: fastcgi
     volumes:
       - source:/PWE
       - project:/PWE/webapps/mydomain.ltd
     deploy:
       replicas: 1
     ports:
       - "7779:7779"
     working_dir: /PWE/examples/generic_web # Set te path to your owner project
     command:
       - ./pwe.fcgi
     stdin_open: true
     tty: true
     environment:
       FCGI_SOCKET_PATH: :7779
       PWE_CONF_DB1_HOST: mysql57
       PWE_CONF_DB1_PORT: 3306
       PWE_CONF_DB1_DBNAME: pwe
       PWE_CONF_DB1_USER: pwe
       PWE_CONF_DB1_PASS: pwe
   nginx:
     image: kukam/pwe-nginx
     restart: always
     container_name: nginx
     stdin_open: true
     tty: true
     volumes:
       #- /etc/nginx/docker.conf:/etc/nginx/conf.d/default.conf
       - source:/PWE:ro
       - project:/PWE/webapps/mydomain.ltd/:ro
     ports:
       - "7778:80"       
volumes:
    source:
    nginx:
    mysql57:
    project:

#networks:
#    pwenet:
#      driver: overlay
#      ipam:
#        driver: default
#        config:
#          - subnet: 172.31.13.0/24 
