version: '3'

services:
   pwe:
     image: kukam/pwe
     volumes:
       - source:/PWE
     restart: on-failure
   pwe-myproject:
     image: kukam/pwe-myproject
     volumes:
       - project:/PWE/webapps/myproject
     restart: on-failure
   database:
     image: kukam/pwe-${DB_DRIVER:-maria}
     restart: unless-stopped
     volumes:
       - ${DB_DRIVER:-maria}:/dbhome
     deploy:
       placement:
         constraints:
           - node.role == manager
     environment:
       DB_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD:-root123}
       DB_NAME: ${DB_NAME:-pwe}
       DB_USER: ${DB_USER:-pwe}
       DB_USER_PASSWORD: ${DB_USER_PASSWORD:-pwe}
   fastcgi:
     image: kukam/pwe-fastcgi
     restart: unless-stopped
     volumes:
       - source:/PWE
       - project:/PWE/webapps/myproject
       - uploadfile:/PWE/webapps/myproject/uploadfile
     stdin_open: true
     tty: true
     environment:
       FCGI_SOCKET_PATH: :7779
       PWE_CONF_pwe_save_opt_to: db
       PWE_CONF_pwe_home: /PWE/webapps/myproject/
       PWE_CONF_pwe_upload_dir: uploadfile/
       PWE_CONF_pwe_opts_dir: sessions/
       PWE_CONF_dbi_db1_dbdriver: ${DB_DRIVER:-maria}
       PWE_CONF_dbi_db1_host: database
       PWE_CONF_dbi_db1_port: 7775
       PWE_CONF_dbi_db1_schema: public
       PWE_CONF_dbi_db1_database: ${DB_NAME:-pwe}
       PWE_CONF_dbi_db1_login: ${DB_USER:-pwe}
       PWE_CONF_dbi_db1_password: ${DB_USER_PASSWORD:-pwe}
       PWE_CONF_dbi_db1_dbversion_file: conf/${DB_DRIVER:-maria}_dbversion.pl
       PWE_CONF_log_logout: STDERR
       PWE_CONF_log_loglevel: 3
       PWE_CONF_log_log_delay: 1
       PWE_CONF_log_log_delay_minimum: 0.1
   webproxy:
     image: kukam/pwe-${WEBSERVER_NAME:-nginx}
     restart: unless-stopped
     stdin_open: true
     tty: true
     volumes:
       - source:/PWE
       - project:/PWE/webapps/myproject
       - uploadfile:/PWE/webapps/myproject/uploadfile
     ports:
       - "7778:80"
volumes:
    source: 		# PWE core code
    maria:			# Maria volume
    postgres:		# Postgres volume
    project:		# My webpage
    uploadfile:		# Uploadfile
