---
apiVersion: v1
kind: Namespace
metadata:
  name: "pwe"
---
apiVersion: v1
kind: Service
metadata:
  name: pwe-maria-svc
  namespace: pwe
spec:
  ports:
  - port: 7775
  selector:
    app: pwe-db
---
apiVersion: v1
kind: Service
metadata:
  name: pwe
  namespace: pwe
spec:
  ports:
  - port: 7779
  selector:
    app: pwe
---
apiVersion: v1
kind: Service
metadata:
  name: pwe-nginx-svc
  namespace: pwe
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: pwe-webproxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pwe-db
  name: pwe-db
  namespace: pwe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pwe-db
  template:
    metadata:
      labels:
        app: pwe-db
    spec:
      containers:
      - image: kukam/pwe-maria:latest
        imagePullPolicy: Always
        name: pwe-maria
        env:
        - name: DB_ADMIN_PASSWORD 
          value: "root123"
        - name: DB_NAME
          value: "pwe"
        - name: DB_USER
          value: "pwe"
        - name: DB_USER_PASSWORD
          value: "pwe"
        ports:
        - containerPort: 7775
          name: pwe-db
        volumeMounts:
        - name: maria-storage
          mountPath: /dbhome
      volumes:
      - name: maria-storage
        emptyDir: {}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: pwe
  name: pwe
  namespace: pwe
spec:
  selector:
    matchLabels:
      app: pwe
  template:
    metadata:
      labels:
        app: pwe
    spec:
      containers:
      - image: kukam/pwe:latest
        imagePullPolicy: Always
        name: pwe
        env:
        - name: PWESOURCE 
          value: "https://github.com/kukam/PWE/trunk"
        - name: MYPROJECT
          value: "https://github.com/kukam/PWE/trunk/examples/generic_web"
        - name: FCGI_SOCKET_PATH
          value: ":7779"
        - name: PWE_CONF_pwe_save_opt_to
          value: "db"
        - name: PWE_CONF_pwe_assets_dir
          value: "assets, uploadfile/"
        - name: PWE_CONF_pwe_upload_dir
          value: "uploadfile/"
        - name: PWE_CONF_pwe_assets_browse_dir
          value: "uploadfile/"
        - name: PWE_CONF_pwe_opts_dir
          value: "sessions/"
        - name: PWE_CONF_dbi_db1_dbdriver
          value: "maria"
        - name: PWE_CONF_dbi_db1_host
          value: "pwe-maria-svc"
        - name: PWE_CONF_dbi_db1_port
          value: "7775"
        - name: PWE_CONF_dbi_db1_schema
          value: "public"
        - name: PWE_CONF_dbi_db1_database
          value: "pwe"
        - name: PWE_CONF_dbi_db1_login
          value: "pwe"
        - name: PWE_CONF_dbi_db1_password
          value: "pwe"
        - name: PWE_CONF_dbi_db1_dbversion_file
          value: "conf/maria_dbversion.pl"
        - name: PWE_CONF_dbi_db1_trayconnect
          value: "10"
        - name: PWE_CONF_log_logout
          value: "STDERR"
        - name: PWE_CONF_log_loglevel
          value: "3"
        - name: PWE_CONF_log_log_delay
          value: "1"
        - name: PWE_CONF_log_log_delay_minimum
          value: "0.1"
        ports:
        - containerPort: 7779
          name: pwe
        volumeMounts:
        - name: pwe-project
          mountPath: /PWE/webapps/myproject
        - name: pwe-uploadfile
          mountPath: /PWE/webapps/myproject/uploadfile
      volumes:
      - name: pwe-project
        emptyDir: {}
      - name: pwe-uploadfile
        emptyDir: {}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: pwe-webproxy
  name: pwe-webproxy
  namespace: pwe
spec:
  selector:
    matchLabels:
      app: pwe-webproxy
  template:
    metadata:
      labels:
        app: pwe-webproxy
    spec:
      containers:
      - image: kukam/pwe-nginx:latest
        imagePullPolicy: Always
        name: pwe-nginx
        ports:
        - containerPort: 80
          name: pwe-webproxy
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pwe-ingress
  namespace: pwe
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - pwe.kube.freebox.cz
    secretName: pwe-secret
  rules:
  - host: pwe.kube.freebox.cz
    http:
      paths:
      - path: /
        backend:
          serviceName: pwe-nginx-svc
          servicePort: 80
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: pwe-certificate
  namespace: pwe
spec:
  secretName: pwe-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: pwe.kube.freebox.cz
  dnsNames:
  - pwe.kube.freebox.cz
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - pwe.kube.freebox.cz
---
apiVersion: v1
kind: Secret
metadata:
  name: pwe-secret
  namespace: pwe
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lKQU1SL0kxZ2h4dHhnTUEwR0NTcUdTSWIzRFFFQkN3VUFNQjR4SERBYUJnTlYKQkFNTUUzQjNaUzVyZFdKbExtWnlaV1ZpYjNndVkzb3dIaGNOTVRnd09ERTFNRGd3TURVM1doY05Namd3T0RFeQpNRGd3TURVM1dqQWVNUnd3R2dZRFZRUUREQk53ZDJVdWEzVmlaUzVtY21WbFltOTRMbU42TUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcHJLcXJSTlZaUlpiNGlyQ2ZucnE2cjZaTDJxNmV4RjIKNXFPQ04wdWtTVTkzaFZYRUZ0MjF2SFQzeVFpQTBZWlRDVGF1ZG1YSDNkT0xnRjRLd2ZOU1BmczlRUjNrUnBMWgpVZGE0Z3NaYmVaUEJwYmpuaS9CTDBBdDVVbU1WSU5YeGVPeVJUR2VPRDBJcWhLSG5zYWxFSnRtVWZJTExqQk10CjhNY1Zkalc2dlZQdWt0ZXNwTVpUS09CczNsT1FWZ3dFR2JTOUxYZkliNnAvWUtWQnBrd2p1TnhWUlc3MXNQSFMKcDRqeTBTZXhaU3N1WlMxUVErenZ6RGFlSzRTWUI1VWE0K21naU9peXFVL1VUbEd0VUYzbDRzNzRjc3hCOGk2YwpYRjNuM3JNVlZBdVMzc0dvUEpGTm1reG52TGZldnVXbThpbGl1MFM5T1M5TXdLNFVlMFBYb1FJREFRQUJvMUF3ClRqQWRCZ05WSFE0RUZnUVVreUNvRGJvM0VYT203STd1TDlCTDh2KytLMjB3SHdZRFZSMGpCQmd3Rm9BVWt5Q28KRGJvM0VYT203STd1TDlCTDh2KytLMjB3REFZRFZSMFRCQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBSWttcEgvTkRvOFJSOS9vbDZrSnZFRTVleGh3YmY0aVB2M2VwWTVIQXd5bGdmV2hpdHNxSzF6YjRDNVFFCjhpZmFYYXNGczNyaVdVZm1WZHFhbVNtS3B2R0o5NmdIbVJvSmFYWHhVWVBRbG9SWCs2UURUb1FvVGh6RlBBWWkKY1BsNVZnU0hRRG5HVEVGZDQxeXp5WFFmUGYyQlg0amhHNzZnZnFYV213K3IydU5qdHZQQ3drdDVvRHdEV2I0eApsK3UxUjdka1c2NW45RUNhYjhwYW9TRmtpbXpzVnJpcURJRlZqL2lnOHl6d2VXK1NleTYvaFRGK0JpZXVYcEVlCmtaM1c3d1I0SEdLQUJ5L2xtMlBEMHJIRDJEL2x3b2F6MGt3NnBKTldDLzRWNDJUbUxsSUc3bExZdHQyVm4vcGUKWHV4MzAwcUhiam9lQ1FOVWwxMEltYjJTTWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ21zcXF0RTFWbEZsdmkKS3NKK2V1cnF2cGt2YXJwN0VYYm1vNEkzUzZSSlQzZUZWY1FXM2JXOGRQZkpDSURSaGxNSk5xNTJaY2ZkMDR1QQpYZ3JCODFJOSt6MUJIZVJHa3RsUjFyaUN4bHQ1azhHbHVPZUw4RXZRQzNsU1l4VWcxZkY0N0pGTVo0NFBRaXFFCm9lZXhxVVFtMlpSOGdzdU1FeTN3eHhWMk5icTlVKzZTMTZ5a3hsTW80R3plVTVCV0RBUVp0TDB0ZDhodnFuOWcKcFVHbVRDTzQzRlZGYnZXdzhkS25pUExSSjdGbEt5NWxMVkJEN08vTU5wNHJoSmdIbFJyajZhQ0k2TEtwVDlSTwpVYTFRWGVYaXp2aHl6RUh5THB4Y1hlZmVzeFZVQzVMZXdhZzhrVTJhVEdlOHQ5Nis1YWJ5S1dLN1JMMDVMMHpBCnJoUjdROWVoQWdNQkFBRUNnZ0VBV0xveXRHcmRBakJUZWQ5dXBLbkNUbTVpMU9WSEd1aGgxRU5sdFE3ekEvNWoKVExvbzVFN2dRODR5Y1hPd05WWDg3cU9IV3dlenlYT25CZzJJUmxIQURiT2psL3hVRytoZitmcURQVUJkUWlvTwpZYW80dkxpTGNkSVpvbXVRdkdpRDNleDFMaWpVYVhTN2N0dEdtcjdRd3FqL0t3TG5Xc2grcEhFakVFZHEvUWhLCk5RWFA5ZFd4clVYbWJTcHY2ZDlFUFh1Q1o3U3U1SXQ3UUtBQ2FSS01Jd09yVW5xNnZQTHVOSXhlQVlJd09FY2YKSlUzNUQ2c0EraEozbmRBeWxIMUlhM080SUM5bHVoUmNCVldIcFN3M253VWJ5L2hUbkk3T2FBMHhiRnZJa2trZAphelVJRy92WHNYMHZuSWd1ekYrVitiZCtSWThMUkRGM0Vlc0gwVGlLRVFLQmdRRGQwVlNKcGZWUHF3SUJUcmd6ClhURVlaWno2V0ZKRU5DNUR2Nk02a1QvbU5LeFF3dGxLMTBUMFdEekFCZzNzL3ZqcFJadTdaZmEzcW9US0J2ZHIKaTNTZTI1NTAva1dtUjZNeWRJMWFhMTNjMlRPOEhIVWJQem1nS0gzTkJvVjFzaEk3eFdBc1drd0YvNEhlNUpOTgpiY1ZDNWxKYTR2ZkZTRmhzd1cyb3JRdEl6UUtCZ1FEQVl0N213czFaQ2wrazczUHVYZEpBdEJvY1BXYXlEZVRRCkJPRkdOY3MvQmlieHdpR083NC9pNHJyMWlZTWdFS0Z0a0gxK0UwY2dBRU5ZVmJrUWVaTHcvanNvN2Z4cDd1eUgKMUZibTlSWjhlNVNKWk8rNmNBbmZLQmw3elFXTjI0cS9GSnQxVU1XRlJUTUx3WmVZQnlCYjREeVNGQm8xQ3NNVQpqQ3UvNWpPYUpRS0JnUUNzNWxwSzRQMlNGKzM4THV3TnZYcGpWZkZDZ2syOXRCN0wyRGpYa2hpSXpFMzB0YXpDClZZSCtKRGxXUkdIZWRmQjNoRGFib0NMcmp4THFsdnVNN0tyK21KbXUvL1F5Wkd5bEM0eVRDbFdqcS9wVGlxc04KamY3UkJEN3E3VVppTTJkYkI4S3JUOGNxZGJzNWpsbnpaTGo2S0tYUkNsR3ZpWEREZFJLUkJERmprUUtCZ1FDSgowVW9rdlVBbG5RelBOc294NC93T1pmYWViRTM1RjRMbWtkaGZWNEgxOEE1TitlZllZVDBPSjZZTzV5ZUwvTjNuCmd5Nmk5bVJwUkViNkxNNmFRcjFFN3BxcXczR2k0WW1IOUZFY3VrNFZkdUg5V3RWeEZYbTg1eGo2V3ZDem9xWk8KSkJFSmhZYzU1VXlnQzFyeGlZbGd4ODRjUjFKTzFSclN5V2M5M1VieUVRS0JnSHJuWXdOVmQ1SG81TEEyOUZnOQpBSkR1NTNSZGZKSElkenV6cFpreGR5TkZ0ZEhKN1JhSlNqNWUzWThLK0IrbU1pUUc0STdIbVV0RkF3RStnODNhClNkYUdrM255VFRpc1B0RDdMMXUvZmsxeFk2Tk9JVll0M0pPejBPM2NGN2ZMQU44RkFuSVhQYlJDa2dHdmJGY3oKRU9UbFFFNUVyaURPOGUyQVA2U21PekFMCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K

      
