---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: pwe-secret
  namespace: pwe
spec:
  secretName: pwe-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: pwe.kube.freebox.cz
  dnsNames:
  - pwe.kube.freebox.cz
  acme:
    config:
    - http01:
        ingress: ""
        ingressClass: nginx
      domains:
      - pwe.kube.freebox.cz
