---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pwe-postgres
  name: pwe-postgres
  namespace: pwe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pwe-postgres
  template:
    metadata:
      labels:
        app: pwe-postgres
    spec:
      containers:
      - image: kukam/pwe-postgres:latest
        imagePullPolicy: Always
        name: pwe-postgres
        env:
        - name: DB_ADMIN_PASSWORD 
          value: "root123"
        - name: DB_NAME
          value: "pwe"
        - name: DB_USER
          value: "pwe"
        - name: DB_USER_PASSWORD
          value: "pwe"
        ports:
        - containerPort: 7775
          name: pwe-db
        volumeMounts:
        - name: maria-storage
          mountPath: /dbhome
      volumes:
      - name: maria-storage
        emptyDir: {}
